#! /usr/bin/perl

=pod
This script uses both .storable to write the HTML-file.

(c) 2020-2022 by kittennbfive
AGPLv3+
THIS CODE IS PROVIDED WITHOUT ANY WARRANTY!
=cut

use strict;
use warnings FATAL=>'all';
use autodie;
use Storable;

my %connections_fpga; #{PIN}->()
%connections_fpga=%{retrieve('connections_fpga.storable')};

my %fpga_pins_cabga256; #{PIN}={pin_func, bank, dual_func}
%fpga_pins_cabga256=%{retrieve('fpga_cabga256_data.storable')};

open my $out, '>', 'result.htm';

print "creating result.htm... ";

my %ic_func=(U29=>'SDRAM', U32=>'SDRAM', U3=>'PHY0', U7=>'PHY1', U9=>'Buffer', U10=>'Buffer', U12=>'Buffer', U15=>'Buffer', U17=>'Buffer', U20=>'Buffer', U21=>'Buffer', U22=>'Buffer', U23=>'Buffer', U24=>'Buffer', U28=>'Buffer');

print $out <<"END1";
<!DOCTYPE html>
<html>
<!-- AUTOGENERATED FILE - DO NOT EDIT -->

<!-- (c) 2020-2022 by kittennbfive -->
<!-- AGPLv3+ -->
<!-- NO WARRANTY! -->
<head>
<meta charset="utf-8" />
<title>5A-75B V7.0 ECP5 FPGA-View</title>
<style>
body { font-family: sans-serif; }

/* show borders */
table, td { border: 1px solid; border-collapse: collapse; }
/* but not on nested tables */
.cell_table { border: none; border-collapse: collapse; width: 100%; }
.cell_table td { border: none; border-collapse: collapse; }

.label { font-weight: bolder; font-size: 200%; }

.bank { text-align: right; }

td.bank { border-left: 1px solid; border-bottom: 1px solid; }
</style>

<script src="data.js"></script>

<script>
function highlight(list, color)
{	
	var i;
	for(i=0; i<list.length; i++)
	{
		var pin="pin_"+list[i];
		document.getElementsByClassName(pin)[0].style="background-color: "+color+";";
	}
}

function ev_click()
{
	var what=document.getElementById("highlight_what").value;
	var color=document.getElementById("highlight_color").value;
	if(what=="con_ic")
	{
		var ic=document.getElementById("highlight_what").selectedOptions[0].dataset.ic;
		highlight(conn_ic.get(ic), color);
	}
	else if(what=="con_header")
	{
		var header=document.getElementById("highlight_what").selectedOptions[0].dataset.header;
		highlight(conn_header.get(header), color);
	}
	else if(what=="bank")
	{
		var bank=document.getElementById("highlight_what").selectedOptions[0].dataset.bank;
		highlight(banks.get(bank), color);
	}
	else
	{
		alert("ev_click: unknown type "+what+" - Please report this bug!");
	}
}
</script>
</head>

<body>
<h1>This is for 5A-75B V7.0 only and provided WITHOUT ANY WARRANTY!</h1>
<table class="main_table">
	<tr>
		<td>&nbsp;</td>
END1

print $out "\t\t<td class=\"label\">$_</td>\n" foreach (1..16);

print $out "\t</tr>\n";

foreach my $letter (qw/A B C D E F G H J K L M N P R T/)
{
	make_row($letter);
}

print $out <<"END2";
</table>
<br>
<div style="float: left;">
<form>
	<label for="highlight_what">Highlight</label>
	<select name="highlight_what" id="highlight_what">
		<optgroup label="Connections to IC">
END2

foreach my $ic (sort { $a=~s/^U//r <=> $b=~s/^U//r } qw/U29 U32 U3 U7 U9 U10 U12 U15 U17 U20 U21 U22 U23 U24 U28/)
{
	print $out "\t\t\t<option value=\"con_ic\" data-ic=\"$ic\">$ic ($ic_func{$ic})</option>\n";
}

print $out <<"END3";
		</optgroup>
		<optgroup label="Pins of Header">
END3

foreach my $headernumber (1..8)
{
	print $out "\t\t\t<option value=\"con_header\" data-header=\"J$headernumber\">J$headernumber</option>\n";
}

print $out <<"END4";
		</optgroup>
		<optgroup label="FPGA bank">
END4

foreach my $bank (qw/0 1 2 3 6 7 8 40/)
{
	print $out "\t\t\t<option value=\"bank\" data-bank=\"$bank\">$bank</option>\n";
}

print $out <<"END5";
	</optgroup>
	</select>
	<label for="highlight_color">with color</label>
	<select name="highlight_color" id="highlight_color">
		<option value="white">Do not highlight</option>
		<option value="red">Red</option>
		<option value="yellow">Yellow</option>
		<option value="blue">Blue</option>
		<option value="green">Green</option>
	</select>
	<input type="button" value="Do it!" id="highlight_button">
</form>
<noscript><p>The highlight function needs Javascript.</p></noscript>
</div>
<div style="float: right;">
<p>&copy; 2020-2022 by <a href="https://github.com/kittennbfive">kittennbfive</a> - AGPLv3+</p>
</div>
<script>
document.getElementById("highlight_button").addEventListener("click", ev_click); 
</script>
</body>

</html>
END5

close $out;

########################################################################

sub make_row
{
	my $letter=shift;
	
	print $out "\t<tr>\n";
	print $out "\t\t<td class=\"label\">$letter</td>\n";

	foreach my $number (1..16)
	{
		my $pin=$letter.$number;
		
		make_cell($pin);
	}
	print $out "\t</tr>\n";
}

sub make_cell
{
	my $pin=shift;
	
	print $out "\t\t<td class=\"pin_$pin\">\n";
	print $out "\t\t\t<table class=\"cell_table\">\n";
	
	print $out "\t\t\t<tr>\n";
	
	my $func=$fpga_pins_cabga256{$pin}->{pin_func};
	print $out "\t\t\t\t<td>",$func,"</td>\n";

	my $bank=$fpga_pins_cabga256{$pin}->{bank};
	print $out "\t\t\t\t<td class=\"bank bank_",$bank,"\">",$bank,"</td>\n";
	
	print $out "\t\t\t</tr>\n";
	print $out "\t\t\t<tr>\n";
	
	print $out "\t\t\t\t<td colspan=\"2\">";
	if($fpga_pins_cabga256{$pin}->{dual_func} ne '')
	{
		print $out $fpga_pins_cabga256{$pin}->{dual_func};
	}
	else
	{
		print $out "&nbsp;";
	}
	print $out "</td>\n";

	print $out "\t\t\t</tr>\n";
	print $out "\t\t\t<tr>\n";

	print $out "\t\t\t\t<td colspan=\"2\">";
	if(exists($connections_fpga{$pin}))
	{
		print $out join("<br>", @{$connections_fpga{$pin}});
	}
	elsif($func=~/^P[LRTB]\d/) 
	{
		print $out "NC?";
	}
	else
	{
		print $out "&nbsp;";
	}
	print $out "</td>\n";

	print $out "\t\t\t</tr>\n";
	
	print $out "\t\t\t</table>\n";
	print $out "\t\t</td>\n";
}

print "done\n\n";
